// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuirpbjwxpuuxnkjosgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aXJwYmp3eHB1dXhua2pvc2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDI2OTYsImV4cCI6MjA1ODY3ODY5Nn0.TowK_bEeKvz08k6Mx-LtMeCJz71PimUKVoSV5-h_xm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);